#!/bin/bash
#
# requires:
#  bash
#  yum
#
set -e

# *** don't install java-1.7.0-openjdk ***
yum install -y java-1.6.0-openjdk
yum install -y jenkins
sed -i "s,^JENKINS_USER=.*,JENKINS_USER=root," /etc/sysconfig/jenkins
