#!/bin/bash
#
# requires:
#  bash
#  yum
#
set -e

# *** don't install java-1.7.0-openjdk ***
yum install -y java-1.6.0-openjdk
yum install -y jenkins
sed -i "s,^JENKINS_USER=.*,JENKINS_USER=root," /etc/sysconfig/jenkins

# install git plugin
base_url="http://updates.jenkins-ci.org/latest"
while read plugin; do
  curl -fsSkL -o /var/lib/jenkins/plugins/${plugin} ${base_url}/${plugin}
done < <(cat <<-EOS
config-autorefresh-plugin.hpi
git.hpi
hipchat.hpi
simple-theme-plugin.hpi
EOS
)

cd  /var/lib/jenkins/jobs
git init
git add .
git commit -m 'kemukins: config keeper.'
